config/routes.rb
Rails.application.routes.draw do
  root 'events#index'

  devise_for :users
  resources  :users, only: :show do
    resources :profil_img, only: :create
  end
  resources  :events do
    resources  :attendances
    resources  :avatars, only: :create
  end

  namespace :admin do
    root 'admin#index'
    resources :users
    resources :admin, only: :index
    resources :events
    resources :attendances, only: :index
  end

end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attendances, dependent: :destroy
  has_many :users, through: :attendances
  belongs_to :admin, class_name: 'User'
  has_one_attached :avatar

  validates :start_date,
    presence: {message: 'Date de départ obligatoire'}
    validate :start_date_is_past

  validates :duration, 
    presence: {message: 'Durée obligatoire'},
    numericality: {greater_than: 0}
    validate :is_duration_multiple_5

  validates :title,
    presence: {message: "Titre obligatoire"},
    length: {in: 5..140}

  validates :description,
    presence: {message: "Description obligatoire"},
    length: {in: 20..1000}

  validates :price,
    presence: {message: "Prix obligatoire"},
    numericality: {only_integer: true, greater_than: 0, less_than: 1000, message: "Le prix doit être compris entre 1 et 1 000"}

  validates :location,
    presence: {message: "Lieu obligatoire"}

  validate :image_attached?
  

  def start_date_is_past
    if start_date.past?
      errors.add(:start_date, "Date non valide")
    end
  end

  def is_duration_multiple_5
    if duration % 5 != 0
      errors.add(:duration, "La durée doit être un multiple de 5")
    end
  end

  def end_date 
    @end_date = start_date + duration*60
  end

  def image_attached?
    if avatar.attached? == false
      errors.add(:avatar, "L'image est obligatoire")
    end
  end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_is_admin

  def index
    @admin = current_user
    @users = User.all 
    @events = Event.all
  end

  def edit 
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(post_params)
      redirect_to admin_root_path, notice: "L'évènement a bien été modifié !"
    else
      flash.now[:messages] = @event.errors.full_messages
      render :edit
    end
    
  end

  def show
    @event = Event.find(params[:id])
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to admin_root_path, notice: "L'évènement a bien été détruit !"
  end

  private

  def post_params
    params.require(:event).permit(:title,:description,:duration,:location,:price,:start_date,:avatar)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except:[:index]
  before_action :is_admin?, except:[:index,:new,:create,:show]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(post_params)
    @event.admin_id = current_user.id
    if @event.save 
      redirect_to root_path, notice: "L'évènement '#{@event.title.capitalize}' a bien été créé ! Félicitation"
    else
      flash.now[:messages] = @event.errors.full_messages
      render new_event_path
    end
  end

  def edit 
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(post_params)
      redirect_to event_path(params[:id]), notice: "L'évènement a bien été modifié !"
    else
      flash.now[:messages] = @event.errors.full_messages
      render :edit
    end
    
  end

  def show
    @event = Event.find(params[:id])
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to root_path, notice: "L'évènement a bien été détruit !"
  end

  private

  def is_admin?
    unless current_user.id == Event.find(params[:id]).admin.id
      flash[:danger] = "Vous n'êtes pas le créateur de cet évènement....Si oui, prouvez le"
      redirect_to root_path
    end
  end

  def post_params
    params.require(:event).permit(:title,:description,:duration,:location,:price,:start_date,:avatar)
  end

end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/edit.html.erb
<div class="container mb-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>
      <%=form_for @event, url: admin_event_path(@event), html: { class: "form-signin mt-3",method: :put } do |f|%>
        <h1 class="h3 mb-3 font-weight-normal text-center">Modifier ton évènement</h1>

        <div class='container'>
          <%if flash[:messages]%>
            <div class="alert alert-danger" role="alert">
              <%flash[:messages].each do |message|%>
                <p><%=message%></p>
              <%end%>
            </div> 
          <%end%>
          <%if flash[:notice]%>
            <div class="alert alert-success" role="alert">
              <p><%=flash[:notice]%></p>
            </div> 
          <%end%>
          <%if flash[:danger]%>
            <div class="alert alert-danger" role="alert">
              <p><%=flash[:danger]%></p>
            </div> 
          <%end%>
        </div>

        <div class='form-group'>
          <label>Titre</label><br>
          <%= f.text_field :title, class: 'form-control'%>
        </div>

        <div class='form-group'>
          <label>Description</label><br>
          <%= f.text_area :description, class:'form-control'%>
        </div>

        <div class='form-group'>
          <label>Durée</label><br>
          <%= f.number_field :duration, class:'form-control'%>
        </div>

        <div class='form-group'>
          <label>Prix</label><br>
          <%= f.number_field :price, class:'form-control'%>
        </div>

        <div class='form-group'>
          <label>Lieu</label><br>
          <%= f.text_field :location, class:'form-control'%>
        </div>  

        <div class='form-group'>
          <label>Date et heure de départ</label><br>
          <%= f.datetime_local_field :start_date, class:'form-control'%>
        </div>  

        <br>

        <div class='form-group'>

          <button type=submit class='btn btn-outline-warning'>Modifier l'évènement</button>

        </div>
      <% end %>

      <%=form_tag event_avatars_path(@event),class: "form-signin mt-3",multipart: true, method: "post" do %>
      <div class='form-group'>
        <%= file_field_tag :avatar, class:'form-control' %>
      </div>
      <div class='form-group'>
        <button type=submit class='btn btn-outline-warning'>Changer l'image</button>
      </div>
      <%end%>
      <%= link_to "Retour", admin_root_path %>
    </div>
  </div>
</div>

app/views/admin/events/index.html.erb
<div class="jumbotron mb-0 py-4 bg-light border-5 border-bottom border-warning">
    <div class="container">
      <h1 class="display-3">Page administrateur<span class='yellow'>
      <%if @admin.first_name != nil %>
        <%=@admin.first_name.capitalize%>
      <%end%></span> </h1>
      <p>Depuis cet espace tu peux tout modifier... GOD mode !!!</p>
  </div>
</div>


<%if flash[:messages]%>
  <div class='container'>
    <div class="alert alert-danger" role="alert">
      <%flash[:messages].each do |message|%>
        <p><%=message%></p>
      <%end%>
    </div> 
  <%end%>
  <%if flash[:notice]%>
    <div class="alert alert-success" role="alert">
      <p><%=flash[:notice]%></p>
    </div> 
  <%end%>
  <%if flash[:danger]%>
    <div class="alert alert-danger" role="alert">
      <p><%=flash[:danger]%></p>
    </div> 
  </div>
<%end%>


<div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link text-dark" href="<%=admin_root_path%>">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                  Dashboard <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-dark" href="<%=admin_events_path%>">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg>
                  Evenements
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-dark" href="<%=admin_users_path%>">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
                  Utilisateurs
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-dark" href="#">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bar-chart-2"><line x1="18" y1="20" x2="18" y2="10"></line><line x1="12" y1="20" x2="12" y2="4"></line><line x1="6" y1="20" x2="6" y2="14"></line></svg>
                  ...
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-dark" href="<%=admin_attendances_path%>">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-layers"><polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline points="2 12 12 17 22 12"></polyline></svg>
                  Réservations
                </a>
              </li>
            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4"><div class="chartjs-size-monitor" style="position: absolute; inset: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
          <h2>Tous les évènements</h2>
          <div class="table-responsive">
            <table class="table table-hover user_table">
              <thead>
                <tr>
                  <th >#ID</th>
                  <th>Titre</th>
                  <th>Description</th>
                  <th>Durée</th>
                  <th>Prix</th>
                  <th>Lieu</th>
                  <th>Date et heure</th>
                  <th>Voir</th>
                  <th>Modifier</th>
                  <th>Supprimer</th>
                </tr>
              </thead>
              <tbody>
              <%@events.sort.each do |event|%>
                <tr>
                  <td><%=event.id%></td>
                  <td><%=event.title%></td>
                  <td><%=event.description%></td>
                  <td><%=event.duration%></td>
                  <td><%=event.price%></td>
                  <td><%=event.location%></td>
                  <td><%=event.start_date%></td>
                  <td><a class="btn btn-outline-success" href="<%=admin_event_path(event.id)%>">Voir</a></td>
                  <td><a class="btn btn-outline-warning" href="<%= edit_admin_event_path(event.id)%>">Modifier</a></td>
                  <td><a class="btn  btn-outline-danger " href=<%=admin_event_path(event)%> data-method='delete' data-confirm='Etes vous sur?'>Supprimer l'évènement'</a></td>
                </tr>
              </tbody>
              <%end%>
            </table>
          </div>
        </main>
      </div>
    </div>

app/views/admin/events/show.html.erb
<div class='containerfluid border-5 border-bottom border-warning'>
  <div class='container my-5'>

    <div class='container'>
      <%if flash[:messages]%>
        <div class="alert alert-danger" role="alert">
          <%flash[:messages].each do |message|%>
            <p><%=message%></p>
          <%end%>
        </div> 
      <%end%>
      <%if flash[:notice]%>
        <div class="alert alert-success" role="alert">
          <p><%=flash[:notice]%></p>
        </div> 
      <%end%>
      <%if flash[:danger]%>
        <div class="alert alert-danger" role="alert">
          <p><%=flash[:danger]%></p>
        </div> 
      <%end%>
    </div>


    <h2><%=@event.title%> <span class='text-muted'>by <%=@event.admin.email%></span></h2>
    <%if @event.avatar.attached?%>
      <%= image_tag @event.avatar, alt: 'avatar', height:300, class:'event_image' %>
    <%end%>  
    <hr>
    <p>Lieu : <%=@event.location%></p>
    <p>Date de début : <%=@event.start_date%></p>
    <p>Date de fin : <%=@event.end_date%>
    <hr>
    <p>Nombre de personnne(s): <%=@event.attendances.size%>
    <p> Prix : <%=@event.price%> €
    <hr class='border-3 border border-warning'>
    <p>Description:</p>
    <p class='mx-5'>>>> <%=@event.description%></p>
  </div>
</div>

<div class='containerfluid'>
  <div class='container '>
  <h2 class='text-center'>Participant(s)</h2>
  <br>
    <table>
      <tr>
        <th>Nom</th>
        <th>Prénom</th>
        <th>Email</th>
      </tr>
      <%@event.attendances.each do |attendance|%>
      <%if attendance.event.id == @event.id%>
      <tr>
        <td><%=attendance.user.last_name%></td>
        <td><%=attendance.user.first_name%></td>
        <td><%=attendance.user.email%></td>
      </tr>
      <%end%>
      <%end%>
  </div>
</div>