config/routes.rb
Rails.application.routes.draw do
  root 'events#index'

  devise_for :users
  resources  :users, only: :show do
    resources :profil_img, only: :create
  end
  resources  :events do
    resources  :attendances
    resources  :avatars, only: :create
  end

  namespace :admin do
    root 'admin#index'
    resources :users
    resources :admin, only: :index
    resources :events
    resources :attendances, only: :index
  end

end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attendances, dependent: :destroy
  has_many :users, through: :attendances
  belongs_to :admin, class_name: 'User'
  has_one_attached :avatar

  validates :start_date,
    presence: {message: 'Date de départ obligatoire'}
    validate :start_date_is_past

  validates :duration, 
    presence: {message: 'Durée obligatoire'},
    numericality: {greater_than: 0}
    validate :is_duration_multiple_5

  validates :title,
    presence: {message: "Titre obligatoire"},
    length: {in: 5..140}

  validates :description,
    presence: {message: "Description obligatoire"},
    length: {in: 20..1000}

  validates :price,
    presence: {message: "Prix obligatoire"},
    numericality: {only_integer: true, greater_than: 0, less_than: 1000, message: "Le prix doit être compris entre 1 et 1 000"}

  validates :location,
    presence: {message: "Lieu obligatoire"}

  validate :image_attached?
  

  def start_date_is_past
    if start_date.past?
      errors.add(:start_date, "Date non valide")
    end
  end

  def is_duration_multiple_5
    if duration % 5 != 0
      errors.add(:duration, "La durée doit être un multiple de 5")
    end
  end

  def end_date 
    @end_date = start_date + duration*60
  end

  def image_attached?
    if avatar.attached? == false
      errors.add(:avatar, "L'image est obligatoire")
    end
  end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_is_admin

  def index
    @admin = current_user
    @users = User.all 
    @events = Event.all
  end

  def edit 
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(post_params)
      redirect_to admin_root_path, notice: "L'évènement a bien été modifié !"
    else
      flash.now[:messages] = @event.errors.full_messages
      render :edit
    end
    
  end

  def show
    @event = Event.find(params[:id])
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to admin_root_path, notice: "L'évènement a bien été détruit !"
  end

  private

  def post_params
    params.require(:event).permit(:title,:description,:duration,:location,:price,:start_date,:avatar)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except:[:index]
  before_action :is_admin?, except:[:index,:new,:create,:show]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(post_params)
    @event.admin_id = current_user.id
    if @event.save 
      redirect_to root_path, notice: "L'évènement '#{@event.title.capitalize}' a bien été créé ! Félicitation"
    else
      flash.now[:messages] = @event.errors.full_messages
      render new_event_path
    end
  end

  def edit 
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(post_params)
      redirect_to event_path(params[:id]), notice: "L'évènement a bien été modifié !"
    else
      flash.now[:messages] = @event.errors.full_messages
      render :edit
    end
    
  end

  def show
    @event = Event.find(params[:id])
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to root_path, notice: "L'évènement a bien été détruit !"
  end

  private

  def is_admin?
    unless current_user.id == Event.find(params[:id]).admin.id
      flash[:danger] = "Vous n'êtes pas le créateur de cet évènement....Si oui, prouvez le"
      redirect_to root_path
    end
  end

  def post_params
    params.require(:event).permit(:title,:description,:duration,:location,:price,:start_date,:avatar)
  end

end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_banner_large.html.erb
<div class='containerfluid  list-group banner_l'>
  <h1 class='text-center text-white py-3'>Tu t'ennuies <span class="text-warning">...</span></h1><br><BR></h1>
  <h4 class='container pl-5 mt-5 text-white text-end'>Fait un tour sur le site et tu trouveras de quoi t'occuper. <br>En plus d'accéder à des milliers d'évènements sur la ville de Pau tu peux créer le tiens !</h4>
  <div class='text-center container'>
    <a href='<%=new_event_path%>' type="button" class="btn btn-outline-warning btn-lg">Lance toi et viens créer ton premier évènement ... </a>
  </div>
</div>

app/views/events/_cards.html.erb
<div class='containerfluid d-flex flex-wrap justify-content-around my-5'>
  <%@events.each do |event|%>
  <div class="card m-3" style="width: 20rem">
    <h3 class="card-header bg-warning"><%=event.title%></h3>
    <div class="card-body">
      <h6 class="card-subtitle text-muted"><%=event.admin.email%></h6>
    </div>
    <%if event.avatar.attached?%>
    <%= image_tag event.avatar, alt: 'avatar', width:'100%'%>
    <%else%>
    <svg xmlns="http://www.w3.org/2000/svg" class="d-block user-select-none" width="100%" height="200" aria-label="Placeholder: Image cap" focusable="false" role="img" preserveAspectRatio="xMidYMid slice" viewBox="0 0 318 180" style="font-size:1.125rem;text-anchor:middle">
    <rect width="100%" height="100%" fill="#868e96"></rect>
    <text x="50%" y="50%" fill="#dee2e6" dy=".3em">Image cap</text>
    </svg>
    <%end%>  
    <div class="card-body">
      <p class="card-text"><%=event.description%></p>
    </div>
    <div class="card-body">
      <a href="<%=event_path(event.id)%>" class="btn btn-sm btn-outline-warning">Détails</a>
    </div>
    <div class="card-footer text-muted">
      <%=event.start_date.to_date%>
    </div>
  </div>
  <%end%>
</div>

app/views/events/_edit_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <%=form_for @event do |f|%>
        <h1 class="h3 mb-2 font-weight-normal text-center">Modifier ton évènement</h1>

        <div class='container'>
          <%if flash[:messages]%>
            <div class="alert alert-danger" role="alert">
              <%flash[:messages].each do |message|%>
                <p><%=message%></p>
              <%end%>
            </div> 
          <%end%>
          <%if flash[:notice]%>
            <div class="alert alert-success" role="alert">
              <p><%=flash[:notice]%></p>
            </div> 
          <%end%>
          <%if flash[:danger]%>
            <div class="alert alert-danger" role="alert">
              <p><%=flash[:danger]%></p>
            </div> 
          <%end%>
        </div>

        <div class='form-group'>
          <label>Titre</label><br>
          <%= f.text_field :title, class: 'form-control'%>
        </div>

        <div class='form-group'>
          <label>Description</label><br>
          <%= f.text_area :description, class:'form-control'%>
        </div>

        <div class='form-group'>
          <label>Durée</label><br>
          <%= f.number_field :duration, class:'form-control'%>
        </div>

        <div class='form-group'>
          <label>Prix</label><br>
          <%= f.number_field :price, class:'form-control'%>
        </div>

        <div class='form-group'>
          <label>Lieu</label><br>
          <%= f.text_field :location, class:'form-control'%>
        </div>  

        <div class='form-group'>
          <label>Date et heure de départ</label><br>
          <%= f.datetime_local_field :start_date, class:'form-control'%>
        </div>  

        <br>

        <div class='form-group'>

          <button type=submit class='btn btn-outline-warning'>Modifier l'évènement</button>

        </div>
      <% end %>
      <%=form_tag event_avatars_path(@event),class: "form-signin mt-3",multipart: true, method: "post" do %>
      <div class='form-group'>
        <%= file_field_tag :avatar, class:'form-control' %>
      </div>
      <div class='form-group mt-2'>
        <button type=submit class='btn btn-outline-warning'>Ajouter une image</button>
      </div>
      <%end%>
      <%= link_to "Retour", root_path %>
    </div>
  </div>
</div>

app/views/events/_new_form.html.erb
<div class="container mb-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>
      <%=form_with model: @event, local: true ,class: "form-signin mt-3" do |f|%>
        <h1 class="h3 mb-3 font-weight-normal text-center">Créer un évènement</h1>

        <div class='container'>
          <%if flash[:messages]%>
            <div class="alert alert-danger" role="alert">
              <%flash[:messages].each do |message|%>
                <p><%=message%></p>
              <%end%>
            </div> 
          <%end%>
          <%if flash[:notice]%>
            <div class="alert alert-success" role="alert">
              <p><%=flash[:notice]%></p>
            </div> 
          <%end%>
          <%if flash[:danger]%>
            <div class="alert alert-danger" role="alert">
              <p><%=flash[:danger]%></p>
            </div> 
          <%end%>
        </div>

        <div class='form-group'>
          <label>Titre</label><br>
          <%= f.text_field :title, class: 'form-control'%>
        </div>

        <div class='form-group'>
          <label>Description</label><br>
          <%= f.text_area :description, class:'form-control'%>
        </div>

        <div class='form-group'>
          <label>Durée</label><br>
          <%= f.number_field :duration, class:'form-control'%>
        </div>

        <div class='form-group'>
          <label>Prix</label><br>
          <%= f.number_field :price, class:'form-control'%>
        </div>

        <div class='form-group'>
          <label>Lieu</label><br>
          <%= f.text_field :location, class:'form-control'%>
        </div>  

        <div class='form-group'>
          <label>Date et heure de départ</label><br>
          <%= f.datetime_local_field :start_date, class:'form-control'%>
        </div> 
        <br>
        <div class='form-group'>
          <%= f.file_field :avatar, class:'form-control' %>
        </div>

        <br>

        <div class='form-group'>

          <button type=submit class='btn btn-outline-warning'>Créer l'évènement</button>

        </div>
        
      <% end %>

      <%= link_to "Retour", root_path %>
    </div>
  </div>
</div>

app/views/events/_resource.html.erb
<div class='containerfluid border-5 border-bottom border-warning'>
  <div class='container my-5'>

    <h2><%=@event.title%> <span class='text-muted'>by <%=@event.admin.email%></span></h2>
    <%if @event.avatar.attached?%>
      <%= image_tag @event.avatar, alt: 'avatar', height:300, class:'event_image' %>
    <%end%>  
    <hr>
    <p>Lieu : <%=@event.location%></p>
    <p>Date de début : <%=@event.start_date%></p>
    <p>Date de fin : <%=@event.end_date%>
    <hr>
    <p>Nombre de personnne(s): <%=@event.attendances.size%>
    <p> Prix : <%=@event.price%> €
    <hr class='border-3 border border-warning'>
    <p>Description:</p>
    <p class='mx-5'>>>> <%=@event.description%></p>
  </div>
</div>

<div class='py-5'>
  <div class='container text-center'>
    <%if current_user.id != @event.admin.id && @event.users.exclude?(current_user.id)%>
      <p>Pour s'inscrire à ce magnifique évènement ça se passe par là</p>
      <br>
      <a class="btn btn-outline-warning" href=<%=new_event_attendance_path(@event.id)%> role="button"><<<<  Goooo  >>>></a>
      <%elsif current_user.id == @event.admin.id%>
      <p>Pour en savoir plus sur mon évènement</p>
      <a class="btn btn-outline-warning" href=<%=event_attendances_path(@event.id)%>>Mon espace évènement</a>
    <%end%>
   </div> 
</div>

app/views/events/edit.html.erb
<div class=mt-2>
  <%=render 'edit_form'%>
</div>

app/views/events/index.html.erb
<div>
  <%=render 'banner_large'%>
  <%=render 'cards'%>
</div>

app/views/events/new.html.erb
<div>
  <%=render 'new_form'%>
</div>

app/views/events/show.html.erb
<div class='mb-5'>
  <%=render 'resource'%>
</div>