config/routes.rb
Rails.application.routes.draw do
  root 'events#index'

  devise_for :users
  resources  :users, only: :show do
    resources :profil_img, only: :create
  end
  resources  :events do
    resources  :attendances
    resources  :avatars, only: :create
  end

  namespace :admin do
    root 'admin#index'
    resources :users
    resources :admin, only: :index
    resources :events
    resources :attendances, only: :index
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :attendances, dependent: :destroy
  has_many :events, through: :attendances
  has_many :events, foreign_key: 'admin_id', class_name: 'Event', dependent: :destroy
  has_one_attached :profil_img

  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :check_is_admin

  def index
    @admin = current_user
    @users = User.all 
    @events = Event.all
  end

  def edit 
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(post_params)
      redirect_to admin_root_path, notice: "L'utilisateur a bien été modifié !"
    else
      flash.now[:messages] = @user.errors.full_messages
      render :edit
    end
    
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_root_path, notice: "L'utilisateur a bien été détruit !"
  end

  private

  def post_params
    params.require(:user).permit(:first_name, :last_name, :description, :email, :admin)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(current_user.id)
  end


end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container mb-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>
      <%= form_for  @user, url: admin_user_path(@user), html: { class: "form-signin mt-3",method: :put } do |f| %>
        <h1 class="h3 mb-3 font-weight-normal text-center">Modification Compte utilisateurs</h1>
        <%if flash[:messages]%>
          <div class="alert alert-danger" role="alert">
            <%flash[:messages].each do |message|%>
              <p><%=message%></p>
            <%end%>
          </div>  
        <%end%>  
        <div class="form-group">
          <%= f.label :first_name, "Prénom" %><br />
          <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :last_name, "Nom" %><br />
          <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :description, "Description" %><br />
          <%= f.text_field :description, autofocus: true, autocomplete: "description", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :email, "Email" %><br />
          <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :admin, "Administrateur" %><br />
          <%= f.check_box :admin, autofocus: true, autocomplete: "admin", class: "" %>
        </div>        
        <div class="actions mt-5">
          <%= f.submit "Modifier", class: "btn btn-lg btn-outline-warning btn-block" %>
        </div>
      <% end %>
      <br>
      <%= link_to "Retour", admin_root_path %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="jumbotron mb-0 py-4 bg-light border-5 border-bottom border-warning">
    <div class="container">
      <h1 class="display-3">Page administrateur<span class='yellow'>
      <%if @admin.first_name != nil %>
        <%=@admin.first_name.capitalize%>
      <%end%></span> </h1>
      <p>Depuis cet espace tu peux tout modifier... GOD mode !!!</p>
  </div>
</div>


<%if flash[:messages]%>
  <div class='container'>
    <div class="alert alert-danger" role="alert">
      <%flash[:messages].each do |message|%>
        <p><%=message%></p>
      <%end%>
    </div> 
  <%end%>
  <%if flash[:notice]%>
    <div class="alert alert-success" role="alert">
      <p><%=flash[:notice]%></p>
    </div> 
  <%end%>
  <%if flash[:danger]%>
    <div class="alert alert-danger" role="alert">
      <p><%=flash[:danger]%></p>
    </div> 
  </div>
<%end%>


<div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link text-dark" href="<%=admin_root_path%>">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                  Dashboard <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-dark" href="<%=admin_events_path%>">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg>
                  Evenements
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-dark" href="<%=admin_users_path%>">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
                  Utilisateurs
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-dark" href="#">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bar-chart-2"><line x1="18" y1="20" x2="18" y2="10"></line><line x1="12" y1="20" x2="12" y2="4"></line><line x1="6" y1="20" x2="6" y2="14"></line></svg>
                  ...
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-dark" href="<%=admin_attendances_path%>">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-layers"><polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline points="2 12 12 17 22 12"></polyline></svg>
                  Réservations
                </a>
              </li>
            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4"><div class="chartjs-size-monitor" style="position: absolute; inset: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
          <h2>Tous les utilisateurs</h2>
          <div class="table-responsive">
            <table class="table table-hover user_table">
              <thead>
                <tr>
                  <th >#ID</th>
                  <th>Prénom</th>
                  <th>Nom</th>
                  <th>Description</th>
                  <th>Email</th>
                  <th>Admin ?</th>
                  <th>Voir</th>
                  <th>Modifier</th>
                  <th>Supprimer</th>
                </tr>
              </thead>
              <tbody>
              <%@users.sort.each do |user|%>
                <tr>
                  <td><%=user.id%></td>
                  <td><%=user.first_name%></td>
                  <td><%=user.last_name%></td>
                  <td><%=user.description%></td>
                  <td><%=user.email%></td>
                  <td><%=user.admin%></td>
                  <td><a class="btn btn-outline-success" href="<%=admin_user_path(user.id)%>">Voir</a></td>
                  <td><a class="btn btn-outline-warning" href="<%= edit_admin_user_path(user.id)%>">Modifier</a></td>
                  <td><a class="btn  btn-outline-danger " href=<%=admin_user_path(user)%> data-method='delete' data-confirm='Etes vous sur?'>Supprimer le compte</a></td>
                </tr>
              </tbody>
              <%end%>
            </table>
          </div>
        </main>
      </div>
    </div>

app/views/admin/users/show.html.erb
<div class='container'>
  <div class='containerfluid mt-5'>

    <div class='container'>
      <%if flash[:messages]%>
        <div class="alert alert-danger" role="alert">
          <%flash[:messages].each do |message|%>
            <p><%=message%></p>
          <%end%>
        </div> 
      <%end%>
      <%if flash[:notice]%>
        <div class="alert alert-success" role="alert">
          <p><%=flash[:notice]%></p>
        </div> 
      <%end%>
      <%if flash[:danger]%>
        <div class="alert alert-danger" role="alert">
          <p><%=flash[:danger]%></p>
        </div> 
      <%end%>
    </div>
  
    <%if @user.profil_img.attached?%>
      <%= image_tag @user.profil_img, alt: 'profil_img', height:150, class:'event_image float-end mt-5' %>
    <%else%>
      <%= image_tag 'incognito.svg' ,alt:'incognito', height:150, class:'event_image float-end mt-5'%>
    <%end%>  
    <h2>Profil utilisateur</h2>
    
    <p>Prénom :<%=@user.first_name%></p>
    <p>Nom :<%=@user.last_name%></p>

    <p>Description : <%=@user.description%>
    <p>Email : <%=@user.email%></p>
  </div>
  <hr>
  <h2>Les évèments crées :</h2>
  <div class="row">
    <%@user.events.each do |event|%>
      <div class="col-md-4 p-5">
        <h2><%=event.title%></h2>
        <%if event.avatar.attached?%>
          <%= image_tag event.avatar, alt: 'avatar', height:100, class:'event_image' %>
        <%end%>  
        <p><%=event.description%></p>
        <p><%=event.start_date.to_date%>
        <p><a class="btn btn-outline-warning" href="href=<%=event_path(event.id)%>" role="button">Détails »</a></p>
      </div>
    <%end%>
  </div>  
</div>